

module CSDC.Parser.AbsCSDC where

-- Haskell module generated by the BNF converter




data CSDC = CSDC [Outer]
  deriving (Eq, Ord, Show, Read)

data Outer
    = Outer String Constructor [Inner]
    | DAOofDAOs String Fields [Tree]
    | Committees String [String]
    | Alias String [String]
    | Predefined [String]
  deriving (Eq, Ord, Show, Read)

data Inner = Inner String Constructor [Inner] | End String
  deriving (Eq, Ord, Show, Read)

data Constructor = Record | Choice ChoiceType
  deriving (Eq, Ord, Show, Read)

data ChoiceType = Enum | OneChoice | MultiChoice
  deriving (Eq, Ord, Show, Read)

data Fields = Fields [String]
  deriving (Eq, Ord, Show, Read)

data Tree = Branch String [Tree] | Leaf String
  deriving (Eq, Ord, Show, Read)

