module CSDC.Parser
  ( parseCSDC
  ) where

import CSDC.Parser.AbsCSDC
import CSDC.Parser.ErrM
import CSDC.Parser.ParCSDC
  ( pCSDC
  , myLexer )

-- | Parser for the CSDC format, reexported from the one generated by BNFC.
parseCSDC :: String -> Either String CSDC
parseCSDC s =
  let
    tokens = myLexer s
  in
    case pCSDC tokens of
      Bad a -> Left a
      Ok a -> Right a
